### ISSUE TITLE
need to publish GodotEx 1.1.11

### ISSUE THREAD

**Issue by jasonswearingen** [altamkp/GodotEx#1]
hi, FYI it looks like you didn't publish GodotEx 1.1.11 to nuget.

you did for `GodotEx.Hosting` and `GodotEx.Async`, but not `GodotEx`

cheers!   I look forward to trying the DI Hosting.

**Comment by Qkabi** [comment]
Hi there, v1.1.11 was a mistake which should have been v1.0.11. I have unlisted all v1.1.11 packages, the latest version should be v1.0.14.

**Comment by altamkp** [comment]
Hi there, v1.1.11 was a mistake which should have been v1.0.11. I have unlisted all v1.1.11 packages, the latest version should be v1.0.14.
