### ISSUE TITLE
Unclear how to use `SettingsServer` with Hosting

### ISSUE THREAD

**Issue by ptlthg** [altamkp/GodotEx#3]
Hey, I'm interesting in using GodotEx for my WIP game, but I'm not sure how to use `SettingsServer` with the dependency injection/hosting.

My main question is how do I configure it? Am I able to directly add the `SettingsServer` class as a singleton and configure the initial settings somewhere, or should I be writing a wrapper service to inject instead of that?

If there could be examples of services to inject in the docs, that'd be appreciated also. I am familiar with dependency injection from ASP.NET, but having an example SettingsServer usage and maybe ILogger would help a lot. 

Thanks

**Comment by altamkp** [comment]
Hi there,

You can reference the [unit test for SettingsServer](https://github.com/altamkp/GodotEx/blob/master/src/GodotEx/test/SettingsTest/SettingsTest.cs) for how to use it. I will update the documentation later on to reflect that.

To use it with hosting, build the `SettingsServer` instance with the `SettingsServerBuilder` and add it to the `IServiceCollection` within the `Host` that you created.

```csharp
public partial class AppHost : Host {
    protected override void ConfigureServices(IServiceCollection services) {
        base.ConfigureServices(services);

        var settingsServer = new SettingsServerBuilder()
            // .With()
            .Build();
        services.AddSingleton(settingsServer);
    }
}
```
