### ISSUE TITLE
make SceneTree public?

### ISSUE THREAD

**Issue by jasonswearingen** [altamkp/GodotEx#4]
Hi, I'd like to ask if there is any technical reason for SceneTree generated classes that prevent it from being public?   If not, would you consider accepting a PR where I make public optional, such as `[SceneTree(isPublic=true)]`?

Thank you

**Comment by altamkp** [comment]
Hi, I am not quite catching what you mean here. Are you using `SceneTree` as an attribute here? The `GodotEx` library shouldn't have an attribute named `SceneTree`.

**Comment by jasonswearingen** [comment]
my appologies, this isn't from GodotEx, it's from a different project!  🫨  (GodotSharp.SourceGenerators)

**Comment by altamkp** [comment]
In this case you should probably find the right person at the Godot's official repo. 😁
