### ISSUE TITLE
Transient dependencies recreated on Reparent

### ISSUE THREAD

**Issue by upta** [altamkp/GodotEx#7]
First off, I wanted to say this library is great, I love how you've just embraced "standard" dotnet DI and made it very clean and easy to use.

I ran into a weird edge case I was curious to get your thoughts on (and maybe those thoughts are just "its an edge case, work around it")

Here's my situation:
- Created a state machine, which is being added with AddTransient (since multiple nodes need their own copies of this state machine)
- Node gets reparented
- Transient dependency gets recreated (and thus its state is lost) out from under the Node's object (which stays the same)

I get what its doing and why, but because it feels "off" and a minor trap compared to how we normally expect dependencies to work when we're doing constructor injection.

Simple work around is to just take the injected dependency and store that instance in another variable in _Ready, sort of like doing constructor injection (in case anyone runs into this in the future).

Anyway, just figured I'd bring up this minor gotcha.

Thanks for the awesome library!

**Comment by altamkp** [comment]
Thanks for your feedback!

I originally designed this library with the main intention to handle singleton dependencies, therefore scoped and transient services are not really supported. As for your case, instead of using the DI for injecting the transient, you may as well just create a new instance with `new` if i doesn't have any other dependencies.

I may work on extending the library to support scoped and transient services in a more convenient way in the future, stay in touch!

**Comment by upta** [comment]
Totally reasonable; I'd imagine that injecting singletons is like 99% of the use cases for DI in a game project 🙂

In my case they do have other dependencies so I preferred to use the injector, but it's a simple enough work around my transient issue with something like this:

```csharp
    [Inject]
    private CardStateMachine _injectStateMachine = null!;
    private CardStateMachine _stateMachine = null!;

    public override void _Ready()
    {
        _stateMachine = _injectStateMachine;
    }
```

And even that wouldn't be necessary if I wasn't doing something funky to cause my node to leave the tree like reparenting.

Thanks again!

**Comment by altamkp** [comment]
Instead of using DI in this case, I think it would be more neat to retrieve a trasient instance from the container by creating a static instance of your derived `Host`. Something like:

```csharp
public partial class AppHost : Host {
    public static AppHost Instance { get; private set; }

    public override void _EnterTree() {
        if (Instance != null) {
            throw new InvalidOperationException("AppHost instance already exists.");
        }
        Instance = this;
    }
}

public partial class CustomNode : Node {
    private CardStateMachine _stateMachine;
    
    public override void _Ready() {
        _stateMachine = AppHost.Instance.GetService<CardStateMachine>();
    }
}
```

**Comment by upta** [comment]
If you're gonna go with the Service Locator pattern anyway, you could just inject IServiceProvider for the same effect:

```csharp
    [Inject]
    private IServiceProvider _serviceProvider;

    public override void _Ready()
    {
        _stateMachine = _serviceProvider.GetRequiredService<CardStateMachine>();
    }
```
